# Generated by Django 3.2 on 2021-04-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='host_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='厂商')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='IP')),
                ('port', models.CharField(blank=True, max_length=50, null=True, verbose_name='端口')),
                ('service', models.CharField(blank=True, max_length=50, null=True, verbose_name='服务')),
                ('banner', models.CharField(blank=True, max_length=50, null=True, verbose_name='banner')),
                ('describe', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='web_assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=50, verbose_name='厂商')),
                ('URL', models.CharField(blank=True, max_length=50, null=True, verbose_name='URL')),
                ('webtitle', models.CharField(blank=True, max_length=50, null=True, verbose_name='系统名称')),
                ('finger', models.CharField(blank=True, max_length=50, null=True, verbose_name='指纹')),
                ('describe', models.CharField(blank=True, max_length=50, null=True, verbose_name='描述')),
            ],
        ),
    ]
